### ISSUE TITLE
Offical Python Package

### ISSUE THREAD

**Issue by chrisdecker1201** [peterhinch/micropython-msgpack#3]
Hello @peterhinch 

thank you for this great package.

Would you be interested to publish your package on pypi.org? I really would love to use upip to install this on my ESP8266

Greets,

Christian

**Comment by peterhinch** [comment]
You can use a tool like [rshell](https://github.com/dhylands/rshell) or [mpremote](https://github.com/micropython/micropython/blob/master/tools/mpremote/README.md) to copy the files to an ESP8266 filesystem.

**Comment by chrisdecker1201** [comment]
Yes. I know this tools. But I would like to have an experience like using pipenv install. I can even provide you with a pipeline for this.

**Comment by leycec** [comment]
Promoting `micropython-msgpack` to PyPI is actually a *great* idea – but perhaps not for the expected reason. As Peter says, the official `mpremote` remote is MicroPython's *de facto* package manager. (`rshell`, on the other hand, is largely unmaintained, non-portable, and irrelevant in 2022.)

Then why would promoting `micropython-msgpack` to PyPI be a *great* idea? **Forwards compatibility** and **namespace parking.** By claiming `micropython-msgpack` on PyPI, you prevent others from doing so. Moreover, MicroPython will *probably* provide a genuine package manager at some point; at that point, PyPI-hosted packaging will suddenly be the MicroPython norm rather than the exception.

**Comment by chrisdecker1201** [comment]
I don't understand how mpremote could be a package manager.

I really would like to use `upip` to get every dependency into my repository. For my project, I've the following workflow. I have a setup.py script, where I describe my dependencies. I can execute it with micropython (unix port) which copy the dependencies into a directory. Now I can execute, copy or mount everything with `mpremote` onto my board (ESP32). Without a python package, I've to copy this library into my repository.

**Comment by Tangerino** [comment]
At least to make a one file library, with one single class.
This would facilitate the code integration into an existing project file especially if your project uses OTA, so not an additional file to upload/handle.

Also ensure it works on MP and regular python since we need to pack/unpack on the server side too.

**Comment by peterhinch** [comment]
> At least to make a one file library, with one single class.

The docs explain the reason for the design: to save resources by using "lazy imports".

> Also ensure it works on MP and regular python

I did not target CPython because [u-msgpack-python](https://github.com/vsergeev/u-msgpack-python) supports it. As explained in the docs, this library was derived from the above with the objective of running on a microcontroller. MessagePack is a standard protocol: you can use any library on the server.

**Comment by peterhinch** [comment]
This package can now be installed to a microcontroller using the official `mpremote` tool.

On CPython options are manual installation or to use [u-msgpack-python](https://github.com/vsergeev/u-msgpack-python).
